/**
 * FolderService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.datasul.technology.webdesk.dm.ws;

public interface FolderService extends java.rmi.Remote {
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createFolder(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverDto[] approvers) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createFolderWithApprovementLevels(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] approversWithLevels, com.datasul.technology.webdesk.dm.ws.ApprovalLevelDto[] levels) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createSimpleFolder(java.lang.String username, java.lang.String password, int companyId, int parentDocumentId, java.lang.String publisherId, java.lang.String documentDescription) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] deleteDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] destroyDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] findRecycledDocuments(java.lang.String user, java.lang.String password, int companyId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] getApprovers(java.lang.String username, java.lang.String password, int companyId, int documentId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getChildren(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getFolder(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getPrivateChildren(java.lang.String username, java.lang.String password, int companyId, int parentDocumentId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getRootFolders(java.lang.String username, java.lang.String password, int companyId, java.lang.String colleagueId) throws java.rmi.RemoteException;
    public com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] getSecurity(java.lang.String username, java.lang.String password, int companyId, int documentId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getSubFolders(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getSubFoldersOnDemand(int companyId, java.lang.String user, java.lang.String password, int parentDocumentId, boolean privateFolder, java.lang.String[] documentTypes, int limit, int lastRowId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getSubFoldersPermission(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId, int permission) throws java.rmi.RemoteException;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getSubPrivateFolders(java.lang.String username, java.lang.String password, int companyId, int documentId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public int getUserPermissions(int companyId, java.lang.String username, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] restoreDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateFolder(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverDto[] approvers) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateFolderWithApprovementLevels(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] approversWithLevels, com.datasul.technology.webdesk.dm.ws.ApprovalLevelDto[] levels) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateSimpleFolder(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
}
