/**
 * DocumentService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.datasul.technology.webdesk.dm.ws;

public interface DocumentService extends java.rmi.Remote {
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] approveDocument(int companyId, java.lang.String userId, java.lang.String password, int documentId, int version, java.lang.String approverId, boolean approved, java.lang.String observation) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public java.lang.String[] copyDocumentToUploadArea(java.lang.String user, java.lang.String password, int companyId, int documentId, int version, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.CopyDocumentDto[] copyDocuments(int companyId, java.lang.String login, java.lang.String password, java.lang.String userId, int[] origins, int destination) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createDocument(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverDto[] approvers, com.datasul.technology.webdesk.dm.ws.RelatedDocumentDto[] relatedDocuments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createDocumentWithApprovementLevels(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] approversWithLevels, com.datasul.technology.webdesk.dm.ws.ApprovalLevelDto[] levels, com.datasul.technology.webdesk.dm.ws.RelatedDocumentDto[] relatedDocuments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createSimpleDocument(java.lang.String username, java.lang.String password, int companyId, int parentDocumentId, java.lang.String publisherId, java.lang.String documentDescription, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] createSimpleDocumentPrivate(java.lang.String username, java.lang.String password, int companyId, int parentDocumentId, java.lang.String documentDescription, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] deleteDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] destroyDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] destroyDocumentApproval(java.lang.String userId, java.lang.String password, int companyId, int documentId, java.lang.String publisherId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] findMostPopularDocuments(java.lang.String username, java.lang.String password, int companyId, java.lang.String colleagueId, int nrResultados) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] findMostPopularDocumentsOnDemand(int companyId, java.lang.String user, java.lang.String password, java.lang.String colleagueId, int limit, int lastRowId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] findRecycledDocuments(java.lang.String user, java.lang.String password, int companyId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getActiveDocument(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] getApprovers(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentApprovementHistoryDto[] getDocumentApprovalHistory(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentApprovalStatusDto[] getDocumentApprovalStatus(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getDocumentByExternalId(java.lang.String username, java.lang.String password, int companyId, java.lang.String externalDocumentnId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public byte[] getDocumentContent(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId, int documentoVersao, java.lang.String nomeArquivo) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentDto[] getDocumentVersion(java.lang.String username, java.lang.String password, int companyId, int documentId, int version, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.RelatedDocumentDto[] getRelatedDocuments(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public int getReportSubjectId(java.lang.String username, java.lang.String password, int companyId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] getSecurity(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public int getUserPermissions(int companyId, java.lang.String username, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public java.lang.String moveDocument(java.lang.String username, java.lang.String password, int companyId, int[] documentIds, java.lang.String colleagueId, int destFolderId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public void removeSecurity(java.lang.String username, java.lang.String password, int companyId, int documentId, int version) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] restoreDocument(java.lang.String user, java.lang.String password, int companyId, int documentId, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateDocument(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverDto[] approvers, com.datasul.technology.webdesk.dm.ws.RelatedDocumentDto[] relatedDocuments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateDocumentConversionStatus(java.lang.String username, java.lang.String password, int companyId, int documentId, int version, int status, java.lang.String msg) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateDocumentWithApprovementLevels(java.lang.String username, java.lang.String password, int companyId, com.datasul.technology.webdesk.dm.ws.DocumentDto[] document, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments, com.datasul.technology.webdesk.dm.ws.DocumentSecurityConfigDto[] security, com.datasul.technology.webdesk.dm.ws.ApproverWithLevelDto[] approversWithLevels, com.datasul.technology.webdesk.dm.ws.ApprovalLevelDto[] levels, com.datasul.technology.webdesk.dm.ws.RelatedDocumentDto[] relatedDocuments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateGroupSecurityType(java.lang.String username, java.lang.String password, int companyId, int documentId, int version, int permissionType, int restrictionType, java.lang.String colleagueId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public com.datasul.technology.webdesk.dm.ws.WebServiceMessage[] updateSimpleDocument(java.lang.String username, java.lang.String password, int companyId, int documentId, java.lang.String publisherId, java.lang.String documentDescription, com.datasul.technology.webdesk.dm.ws.Attachment[] attachments) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
    public java.lang.String validateIntegrationRequirements(java.lang.String username, java.lang.String password, int companyId) throws java.rmi.RemoteException, com.datasul.technology.webdesk.dm.ws.Exception;
}
